//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SizeOnDisk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SizeOnDisk.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attr..
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating.
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder....
        /// </summary>
        public static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string DateCreation {
            get {
                return ResourceManager.GetString("DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last access.
        /// </summary>
        public static string DateLastAccess {
            get {
                return ResourceManager.GetString("DateLastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last write.
        /// </summary>
        public static string DateLastWrite {
            get {
                return ResourceManager.GetString("DateLastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk size.
        /// </summary>
        public static string DiskSize {
            get {
                return ResourceManager.GetString("DiskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Folder.
        /// </summary>
        public static string FileTypeFolder {
            get {
                return ResourceManager.GetString("FileTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} File.
        /// </summary>
        public static string FileTypeUnkown {
            get {
                return ResourceManager.GetString("FileTypeUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FolderCount {
            get {
                return ResourceManager.GetString("FolderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drive free.
        /// </summary>
        public static string HardDriveFree {
            get {
                return ResourceManager.GetString("HardDriveFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drive usage.
        /// </summary>
        public static string HardDriveUsage {
            get {
                return ResourceManager.GetString("HardDriveUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument         xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; PagePadding=&quot;4&quot; 
        ///                          FontSize=&quot;{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}, Path=FontSize}&quot; 
        ///                          FontFamily=&quot;{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}, Path=FontFamily}&quot; IsOptimalParagraphEnabled=&quot;True&quot;&gt;
        ///                &lt;Table CellSp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LegendDocument {
            get {
                return ResourceManager.GetString("LegendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        public static string Recalculate {
            get {
                return ResourceManager.GetString("Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        public static string RunAsAdministrator {
            get {
                return ResourceManager.GetString("RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run time.
        /// </summary>
        public static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size format.
        /// </summary>
        public static string SizeFormat {
            get {
                return ResourceManager.GetString("SizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of file disk usage in the selected folder.
        /// </summary>
        public static string TotalDiskSize {
            get {
                return ResourceManager.GetString("TotalDiskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of files in the selected folder.
        /// </summary>
        public static string TotalFiles {
            get {
                return ResourceManager.GetString("TotalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of file size in the selected folder.
        /// </summary>
        public static string TotalFileSize {
            get {
                return ResourceManager.GetString("TotalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of folders in the selected folder.
        /// </summary>
        public static string TotalFolders {
            get {
                return ResourceManager.GetString("TotalFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISizeFormatType.
        /// </summary>
        public static string UISizeFormatType {
            get {
                return ResourceManager.GetString("UISizeFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string UISizeFormatType_Bytes {
            get {
                return ResourceManager.GetString("UISizeFormatType_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor of 1024.
        /// </summary>
        public static string UISizeFormatType_FactorBy1024 {
            get {
                return ResourceManager.GetString("UISizeFormatType_FactorBy1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBytes.
        /// </summary>
        public static string UISizeFormatType_KBytes {
            get {
                return ResourceManager.GetString("UISizeFormatType_KBytes", resourceCulture);
            }
        }
    }
}
